name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::985539772981:role/github-jgpjuniorj"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "jgpjuniorj-sa-east-1-terraform-statefile"
