name: Deploy Terraform

on:
  push:
    branches:
      - main  # Acionar o deploy no push para a branch principal

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v3

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1  # Corrigido para 'aws-region'

      - name: Configurar o Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Planejar Terraform
        run: terraform plan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
